In [11]:
import uproot
tree = uproot.open("opt0finder-art.flat.caf.root:recTree")

In [22]:
for key in tree.keys():
    if (("slc" in key) & ("self" in key)):
        print(key)

rec.slc.self

In [23]:
tree.arrays(["rec.slc.self",
             "rec.slc.opt0.hypoPE",
             "rec.slc.opt0.measPE",
             "rec.slc.opt0.score",
             "rec.slc.opt0.time",
             "rec.slc.opt0.tpc"],library="pd")

                rec.slc.self  rec.slc.opt0.hypoPE  rec.slc.opt0.measPE  \
entry subentry
0     0                   78         62142.414062            61.427502
      1                   77         69281.648438         83388.468750
      2                    0                  NaN                  NaN
      3                    1                  NaN                  NaN
      4                    3                  NaN                  NaN
      5                    4                  NaN                  NaN
      6                    5                  NaN                  NaN
      7                    6                  NaN                  NaN
      8                    8                  NaN                  NaN
      9                    9                  NaN                  NaN
      10                  10                  NaN                  NaN
      11                  11                  NaN                  NaN
      12                  13                  NaN                  NaN
1     0                  120         62089.925781         27701.224609
      1                  116         25434.195312          3020.145020
      2                  118          4012.915527          3020.145020
      3                  117         20759.763672         27701.224609
      4                  119          6410.271973         27701.224609
      5                    0                  NaN                  NaN
      6                    1                  NaN                  NaN
      7                    2                  NaN                  NaN
      8                    3                  NaN                  NaN
      9                    4                  NaN                  NaN
      10                   5                  NaN                  NaN
      11                   6                  NaN                  NaN
      12                   9                  NaN                  NaN
      13                  11                  NaN                  NaN
      14                  13                  NaN                  NaN
      15                  15                  NaN                  NaN
      16                  16                  NaN                  NaN
      17                  18                  NaN                  NaN
2     0                   53         64336.714844         42363.277344
      1                   52         86340.773438        130242.296875
      2                   54          8059.209961         42363.277344
      3                    0                  NaN                  NaN
      4                    1                  NaN                  NaN
      5                    4                  NaN                  NaN
      6                    6                  NaN                  NaN
      7                    7                  NaN                  NaN
      8                    9                  NaN                  NaN
3     0                   34         35822.839844         45564.722656
      1                    0                  NaN                  NaN
      2                    1                  NaN                  NaN
      3                    2                  NaN                  NaN
      4                    4                  NaN                  NaN
      5                    5                  NaN                  NaN
      6                    6                  NaN                  NaN
      7                    7                  NaN                  NaN
      8                    8                  NaN                  NaN
      9                    9                  NaN                  NaN

                rec.slc.opt0.score  rec.slc.opt0.time  rec.slc.opt0.tpc
entry subentry
0     0                   9.867955           1.042981                 0
      1               26787.039062           1.024049                 1
      2                        NaN                NaN       -2147483648
      3                        NaN                NaN       -2147483648
      4                        NaN                NaN       -2147483648
      5                        NaN                NaN       -2147483648
      6                        NaN                NaN       -2147483648
      7                        NaN                NaN       -2147483648
      8                        NaN                NaN       -2147483648
      9                        NaN                NaN       -2147483648
      10                       NaN                NaN       -2147483648
      11                       NaN                NaN       -2147483648
      12                       NaN                NaN       -2147483648
1     0                   5.430081           0.162870                 0
      1                  32.159878           0.161436                 1
      2                  18.743057           0.161436                 1
      3               11455.468750           0.162870                 0
      4                  40.646076           0.162870                 0
      5                        NaN                NaN       -2147483648
      6                        NaN                NaN       -2147483648
      7                        NaN                NaN       -2147483648
      8                        NaN                NaN       -2147483648
      9                        NaN                NaN       -2147483648
      10                       NaN                NaN       -2147483648
      11                       NaN                NaN       -2147483648
      12                       NaN                NaN       -2147483648
      13                       NaN                NaN       -2147483648
      14                       NaN                NaN       -2147483648
      15                       NaN                NaN       -2147483648
      16                       NaN                NaN       -2147483648
      17                       NaN                NaN       -2147483648
2     0                  65.058846           1.358413                 0
      1               65792.437500           1.356458                 1
      2                  10.517646           1.358413                 0
      3                        NaN                NaN       -2147483648
      4                        NaN                NaN       -2147483648
      5                        NaN                NaN       -2147483648
      6                        NaN                NaN       -2147483648
      7                        NaN                NaN       -2147483648
      8                        NaN                NaN       -2147483648
3     0                  42.260632           0.265522                 1
      1                        NaN                NaN       -2147483648
      2                        NaN                NaN       -2147483648
      3                        NaN                NaN       -2147483648
      4                        NaN                NaN       -2147483648
      5                        NaN                NaN       -2147483648
      6                        NaN                NaN       -2147483648
      7                        NaN                NaN       -2147483648
      8                        NaN                NaN       -2147483648
      9                        NaN                NaN       -2147483648